spring:
  cloud:
    gateway:
      routes:
        - id: agro-admin-be
          uri: http://host.docker.internal:8080
          predicates:
            - Path=/**
          metadata:
            connect-timeout: 100000
            response-timeout: 100000