spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "https://agro-admin-fe.onrender.com/"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PATCH
              - PUT
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
        add-to-simple-url-handler-mapping: true
      routes:
        - id: agro-admin-be
          uri: https://agriculture-administration-app-be.onrender.com
          predicates:
            - Path=/**
          metadata:
            connect-timeout: 100000
            response-timeout: 100000
server:
  port: 8080
